name: Build

on:
  push:
    branches: [ "2.0" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Write Nexus Key
        id: nexus_gpg_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'nexus-key.gpg'
          encodedString: ${{ secrets.NEXUSKEY64 }}

      - name: Execute Gradle build
        run: ./gradlew build