name: Build

on:
  push:
    branches: [ "2.0" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Execute Gradle build
        run: ./gradlew build